sns_applicatin/flaskr/views.py
# views.py
from datetime import datetime
from operator import sub

from flask import (
    Blueprint, abort, request, render_template,
    redirect, url_for, flash, session, jsonify
)
from flask_login import (
    login_user, login_required, logout_user, current_user
)
from wtforms.fields.simple import PasswordField
from flaskr.models import (
    User, PasswordResetToken, UserConnect,
    Message
)
from flaskr import db

from flaskr.forms import (
    LoginForm, RegisterForm, ResetPasswordForm,
    ForgotPasswordForm, UserForm, ChangePasswordForm,
    UserSearchForm, ConnectForm, MessageForm
)
from flaskr.utils.message_format import make_message_format, make_old_message_format

bp = Blueprint('app', __name__, url_prefix='')

@bp.route('/')
def home():
    friends = requested_friends = requesting_friends = None
    connect_form = ConnectForm()
    session['url'] = 'app.home'
    if current_user.is_authenticated:
        friends = User.select_friends()
        requested_friends = User.select_requested_friends()
        requesting_friends = User.select_requesting_friends()
    return render_template(
        'home.html',
        friends = friends,
        requested_friends = requested_friends,
        requesting_friends = requesting_friends,
        connect_form = connect_form
    )

@bp.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('app.home'))

@bp.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    if request.method == 'POST' and form.validate():
        user =  User.select_user_by_email(form.email.data)
        if user and user.is_active and user.validate_password(form.password.data):
            login_user(user, remember=True)
            next = request.args.get('next')
            if not next:
                next = url_for('app.home')
            return redirect(next)
        elif not user:
            flash('存在しないユーザーです')
        elif not user.is_active:
            flash('無効なユーザーです。パスワードを再設定してください')
        elif not user.validate_password(form.password.data):
            flash('メールアドレスとパスワードの組み合わせが誤っています')
    return render_template('login.html', form=form)

@bp.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm(request.form)
    if request.method == 'POST' and form.validate():
        user = User(
            username = form.username.data,
            email = form.email.data
        )
        with db.session.begin(subtransactions=True):
            user.create_new_user()
        db.session.commit()
        token = ''
        with db.session.begin(subtransactions=True):
            token = PasswordResetToken.publish_token(user)
        db.session.commit()
        # メールに飛ばすほうがいい
        print(
            f'パスワード設定用URL: http://127.0.0.1:5000/reset_password/{token}'
        )
        flash('パスワード設定用のURLをお送りしました。ご確認ください')
        return redirect(url_for('app.login'))
    return render_template('register.html', form=form)

@bp.route('/reset_password/<uuid:token>', methods=['POST', 'GET'])
def reset_password(token):
    form = ResetPasswordForm(request.form)
    reset_user_id = PasswordResetToken.get_user_id_by_token(token)
    if not reset_user_id:
        abort(500)
    if request.method == 'POST' and form.validate():
        password = form.password.data
        user = User.select_user_by_id(reset_user_id)
        with db.session.begin(subtransactions=True):
            user.save_new_password(password)
            PasswordResetToken.delete_token(token)
        db.session.commit()
        flash('パスワードを更新しました')
        return redirect(url_for('app.login'))
    return render_template('reset_password.html', form=form)

@bp.route('forgot_password', methods=['GET', 'POST'])
def forgot_password():
    form = ForgotPasswordForm(request.form)
    if request.method == 'POST' and form.validate():
        email = form.email.data
        user = User.select_user_by_email(email)
        if user:
            with db.session.begin(subtransactions=True):
                token = PasswordResetToken.publish_token(user)
            db.session.commit()
            reset_url = f'http://127.0.0.1:5000/reset_password/{token}'
            print(reset_url)
            flash('パスワード再登録用のURLを発行しました')
        else:
            flash('存在しないユーザーです')
    return render_template('forgot_password.html', form=form)

@bp.route('/user', methods=['GET', 'POST'])
@login_required
def user():
    form = UserForm(request.form)
    if request.method == 'POST' and form.validate():
        user_id = current_user.get_id()
        user = User.select_user_by_id(user_id)
        with db.session.begin(subtransactions=True):
            user.username = form.username.data
            user.email = form.email.data
            file = request.files[form.picture_path.name].read()
            if file:
                file_name = user_id + '_' + \
                    str(int(datetime.now().timestamp())) + '.jpg'
                picture_path = 'flaskr/static/user_image/' + file_name
                open(picture_path, 'wb').write(file)
                user.picture_path = 'user_image/' + file_name
        db.session.commit()
        flash('ユーザー情報の更新に成功しました')
    return render_template('user.html', form=form)

@bp.route('change_password', methods=['GET', 'POST'])
@login_required
def change_password():
    form = ChangePasswordForm(request.form)
    if request.method == 'POST' and form.validate():
        user = User.select_user_by_id(current_user.get_id())
        password = form.password.data
        with db.session.begin(subtransactions=True):
            user.save_new_password(password)
        db.session.commit()
        flash('パスワードの更新に成功しました')
        return redirect(url_for('app.user'))
    return render_template('change_password.html', form=form)

@bp.route('/user_search', methods=['GET'])
@login_required
def user_search():
    form = UserSearchForm(request.form)
    connect_form = ConnectForm()
    session['url'] = 'app.user_search'
    users = None
    user_name = request.args.get('username', None, type=str)
    next_url = prev_url = None
    if user_name:
        page = request.args.get('page', 1, type=int)
        posts = User.search_by_name(user_name, page)
        next_url = url_for('app.user_search', page=posts.next_num, username=user_name) if posts.has_next else None
        prev_url = url_for('app.user_search', page=posts.prev_num, username=user_name) if posts.has_prev else None
        users = posts.items
        # UserテーブルとUserConnectテーブルを紐付けて、statusを見る
        # from_user_id = 自分のID, to_user_id = 相手のID, status = 1 自分から友達申請中
        # to_user_id = 自分のID, from_user_id = 相手のID, status = 1 相手から友達申請中
        # status = 2の場合、友達申請承認済み
        # レコードが存在しない場合、友達申請が行われていない
    return render_template(
        'user_search.html', form=form, connect_form=connect_form,
        users=users, next_url=next_url, prev_url=prev_url
    )

@bp.route('/connect_user', methods=['POST'])
@login_required
def connect_user():
    form = ConnectForm(request.form)
    if request.method == 'POST' and form.validate():
        if form.connect_condition.data == 'connect':
            new_connect = UserConnect(current_user.get_id(), form.to_user_id.data)
            with db.session.begin(subtransactions=True):
                new_connect.create_new_connect()
            db.session.commit()
        elif form.connect_condition.data == 'accept':
            # 相手から自分へのUserConnectを取得
            connect = UserConnect.select_by_from_user_id(form.to_user_id.data)
            if connect:
                with db.session.begin(subtransactions=True):
                    connect.update_status() # status 1 => 2
                db.session.commit()
    next_url = session.pop('url', 'app:home')
    return redirect(url_for(next_url))

@bp.route('/message/<id>', methods=['GET', 'POST'])
@login_required
def message(id):
    if not UserConnect.is_friend(id):
        return redirect(url_for('app.home'))
    form = MessageForm(request.form)
    # 自分と相手のやり取りのメッセージを取得
    messages = Message.get_friend_messages(current_user.get_id(), id)
    user = User.select_user_by_id(id)
    # まだ読まれていないが、新たに読まれるメッセージ
    read_message_ids = [ message.id for message in messages if ( not message.is_read) and (message.from_user_id == int(id)) ]
    # すでに読まれていて、かつまだチェックしていない自分のメッセージをチェックする
    not_checked_message_ids = [message.id for message in messages if message.is_read and (not message.is_checked) and (message.from_user_id == int(current_user.get_id()))]
    if not_checked_message_ids:
        with db.session.begin(subtransactions=True):
            Message.update_is_checked_by_ids(not_checked_message_ids)
        db.session.commit()
    # read_message_idsのis_readをTrueに変更
    if read_message_ids:
        with db.session.begin(subtransactions=True):
            Message.update_is_read_by_ids(read_message_ids)
        db.session.commit()
    if request.method == 'POST' and form.validate():
        new_message = Message(current_user.get_id(), id, form.message.data)
        with db.session.begin(subtransactions=True):
            new_message.create_message()
        db.session.commit()
        return redirect(url_for('app.message', id=id))
    return render_template(
        'message.html', form=form,
        messages=messages, to_user_id=id,
        user=user
    )

@bp.route('/message_ajax', methods=['GET'])
@login_required
def message_ajax():
    user_id = request.args.get('user_id', -1, type=int)
    # まだ読んでいない相手からのメッセージを取得
    user = User.select_user_by_id(user_id)
    not_read_messages = Message.select_not_read_messages(user_id, current_user.get_id())
    not_read_message_ids = [message.id for message in not_read_messages]
    if not_read_message_ids:
        with db.session.begin(subtransactions=True):
            Message.update_is_read_by_ids(not_read_message_ids)
        db.session.commit()
    # すでに読まれた自分のメッセージでまだチェックしていないものを取得

sns_applicatin/flaskr/templates/_formhelpers.html
{% macro render_field(field) %}
<dt>
    {{ field.label }}
    <dd>
        {{ field(**kwargs) | safe }}
        {% if field.errors %}
        <ul class="errors">
            {% for error in field.errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </dd>
</dt>
{% endmacro %}

sns_applicatin/flaskr/templates/base.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <title>{% block title %}FLASK SNS{% endblock %}</title>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
        <link rel="icon" href="{{ url_for('static', filename='icon/flask.png') }}">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{{url_for('app.home')}}">
                ホーム
            </a>
            {% if current_user.is_authenticated %}
            <a class="navbar-brand" href="{{url_for('app.logout')}}">
                ログアウト
            </a>
            <a class="navbar-brand" href="{{url_for('app.user')}}">
                ユーザー情報編集
            </a>
            <a class="navbar-brand" href="{{url_for('app.user_search')}}">
                ユーザー検索
            </a>
            {% else %}
            <a class="navbar-brand" href="{{url_for('app.login')}}">
                ログイン
            </a>
            <a class="navbar-brand" href="{{url_for('app.register')}}">
                登録
            </a>
            {% endif %}
        </nav>
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

sns_applicatin/flaskr/templates/change_password.html
{% from "_formhelpers.html" import render_field %}
{% extends "base.html" %}
{% block title %}
パスワード変更画面 - {{ super() }}
{% endblock %}
{% block content %}
<h1>パスワード変更画面</h1>
<div class="row">
    <form method='POST'>
        {{ form.csrf_token }}
        {{ render_field(form.password) }}
        {{ render_field(form.confirm_password) }}
        {{ form.submit() }}
    </form>
</div>
{% endblock %}

sns_applicatin/flaskr/templates/forgot_password.html
{% from "_formhelpers.html" import render_field %}
{% extends "base.html" %}
{% block title %}
パスワード再発行 - {{ super() }}
{% endblock %}
{% block content %}
{% for message in get_flashed_messages() %}
{{ message }}
{% endfor %}
<h1>パスワード再発行画面</h1>
<div class="row">
    <form method='POST'>
        {{ form.csrf_token }}
        {{ render_field(form.email) }}
        {{ form.submit() }}
    </form>
</div>
{% endblock %}

sns_applicatin/flaskr/templates/home.html
{% extends "base.html" %}
{% block title %}
ホーム - {{ super() }}
{% endblock %}
{% block content %}
<div class="row">
    {% if current_user.is_authenticated %}
    <div class="col-lg-2 offset-lg-2">
        {% if current_user.picture_path %}
            <img class="user-image-big" src="{{url_for('static', filename=current_user.picture_path)}}">
        {% endif %}
    </div>
    <div class="col-lg-4 offset-lg-2">
        <p>ユーザー名: {{ current_user.username }}</p>
        <p>メールアドレス: {{ current_user.email }}</p>
    </div>
    <div class="col-lg-8 offset-lg-2">
        <h2>友達一覧</h2>
        <table class="table table-bordered">
            {% for friend in friends %}
                <tr>
                    {% if friend.picture_path %}
                    <td><img class="user-image-small" src="{{url_for('static', filename=friend.picture_path)}}"></td>
                    {% else %}
                    <td></td>
                    {% endif %}
                    <td>{{ friend.username }}</td>
                    <td><a href="{{ url_for('app.message', id=friend.id) }}" class="btn btn-link">メッセージを送る</a></td>
                </tr>
            {% endfor %}
        </table>
    </div>
    <div class="col-lg-8 offset-lg-2">
        <h2>以下の人が友達申請しています</h2>
        <table class="table table-bordered">
            {% for friend in requested_friends %}
                <tr>
                    {% if friend.picture_path %}
                    <td><img class="user-image-small" src="{{url_for('static', filename=friend.picture_path)}}"></td>
                    {% else %}
                    <td></td>
                    {% endif %}
                    <td>{{ friend.username }}</td>
                    <td>
                        <form method="POST" action="{{ url_for('app.connect_user') }}">
                            {{ connect_form.csrf_token }}
                            {{ connect_form.connect_condition(value='accept') }}
                            {{ connect_form.to_user_id(value=friend.id) }}
                            {{ connect_form.submit(class='btn btn-primary', value='友達申請を承認する') }}
                        </form>
                    </td>
                </tr>
            {% endfor %}
        </table>
    </div>
    <div class="col-lg-8 offset-lg-2">
        <h2>承認待ちの友達です</h2>
        <table class="table table-bordered">
            {% for friend in requesting_friends %}
            <tr>
                {% if friend.picture_path %}
                <td><img class="user-image-small" src="{{url_for('static', filename=friend.picture_path)}}"></td>
                {% else %}
                <td></td>
                {% endif %}
                <td>{{ friend.username }}</td>
                {% endfor %}
            </tr>
        </table>
    </div>
    {% else %}
        <p>ログイン or 登録をしてください</p>
    {% endif %}
</div>
{% endblock %}

sns_applicatin/flaskr/templates/login.html
{% from "_formhelpers.html" import render_field %}
{% extends "base.html" %}
{% block title %}
ログイン - {{ super() }}
{% endblock %}
{% block content %}
{% for message in get_flashed_messages() %}
{{ message }}
{% endfor %}
<div class="row">
    <form method='POST'>
        {{ form.csrf_token }}
        {{ render_field(form.email) }}
        {{ render_field(form.password) }}
        {{ render_field(form.confirm_password) }}
        {{ form.submit() }}
    </form>
    <a href="{{url_for('app.forgot_password')}}">
        パスワードを忘れた場合
    </a>
</div>
{% endblock %}

sns_applicatin/flaskr/templates/message.html
{% from "_formhelpers.html" import render_field %}
{% extends "base.html" %}
{% block title %}
メッセージ画面 - {{ super() }}
{% endblock %}
{% block content %}
<script>
    $(function(){
        // 5秒間隔でget_new_messagesを実行
        timer = setInterval("get_new_messages()", 5000);
        // 初期表示で画面の一番下に行く
        var scroll = (document.scrollingElement || document.body);
        scroll.scrollTop = scroll.scrollHeight;
    });
    user_id = "{{ to_user_id }}";
    offset_value = 1;
    function get_new_messages(){
        $.getJSON("/message_ajax", {
            user_id: user_id
        }, function(data){
            $('#message-form').before(data['data']);
            var checked_message_ids = data['checked_message_ids'];
            for(let idx = 0; idx < checked_message_ids.length; idx++){
                $('#self-message-tag-'+checked_message_ids[idx]).append('<p>既読</p>');
            }
        });
    };
    function load_old_messages(){
        $.getJSON("/load_old_messages",{
            user_id: user_id,
            offset_value: offset_value
        }, function(data){
            if(data['data']){
                hidden_id = "load_message_" + offset_value;
                hidden_tag = '<div id="' + hidden_id + '"></div>'
                $(hidden_tag).insertAfter("#load_message_button");
                $(data['data']).insertAfter('#load_message_button');
                $('body, html').animate({scrollTop: $("#" + hidden_id).offset().top}, 0);
                offset_value += 1;
            }
        });
    };
</script>
<div class="row">
    <div id="load_message_button" class="col-12">
        <button class="col-12 btn btn-light btun-outline-primary" onclick="load_old_messages();">100件読み込む</button>
    </div>
    {% for message in messages|reverse %}
        {% if message.from_user_id == current_user.id %}
        <div id="self-message-tag-{{message.id}}" class="col-lg-1 offset-lg-6 col-md-1 offset-md-2 col-sm-1 offset-sm-1 col-1">
            {% if message.is_checked %}
                <p>既読</p>
            {% endif %}
        </div>
        <div class="speech-bubble-self col-lg-4 col-md-8 col-sm-8 col-9">
            {% for splitted_message in message.message | replace_newline %}
                <p>{{ splitted_message | urlize }}</p>
            {% endfor %}
        </div>
        <div class="col-lg-1 col-md-1 col-sm-2 col-2">
            {% if current_user.picture_path %}
                <img class="user-image-mini" src="{{ url_for('static', filename=current_user.picture_path) }}">
            {% endif %}
            <p>{{ current_user.username }}</p>
        </div>
        {% else %}
        <div class="speech-bubble-dest col-lg-4 col-md-8 col-sm-8 col-9">
            {% for splitted_message in message.message | replace_newline %}
                <p>{{ splitted_message | urlize }}</p>
            {% endfor %}
        </div>
        <div class="col-lg-1 col-md-1 col-sm-2 col-2">
            {% if user.picture_path %}
                <img class="user-image-mini" src="{{ url_for('static', filename=user.picture_path) }}">
            {% endif %}
            <p>{{ user.username }}</p>
        </div>
        <div class="col-lg-7 col-md-3 col-sm-1 col-1"></div>
        {% endif %}
    {% endfor %}
    <div id="message-form" class="col-lg-4 offset-lg-7 col-md-8 offset-md-4 col-sm-12 col-12">
        <form method="POST">
            {{ form.csrf_token }}
            {{ form.to_user_id(value=to_user_id) }}
            {{ render_field(form.message, cols="50", rows="5") }}
            {{ form.submit() }}
        </form>
    </div>
</div>
{% endblock %}

sns_applicatin/flaskr/templates/register.html
{% from "_formhelpers.html" import render_field %}
{% extends "base.html" %}
{% block title %}
ユーザー登録 - {{ super() }}
{% endblock %}
{% block content %}
<h1>ユーザー情報登録画面</h1>
<div class="row">
    <form method='POST'>
        {{ form.csrf_token }}
        {{ render_field(form.username) }}
        {{ render_field(form.email) }}
        {{ form.submit() }}
    </form>
</div>
{% endblock %}

sns_applicatin/flaskr/templates/reset_password.html
{% from "_formhelpers.html" import render_field %}
{% extends "base.html" %}
{% block title %}
パスワード登録 - {{ super() }}
{% endblock %}
{% block content %}
<h1>パスワード登録画面</h1>
<div class="row">
    <form method='POST'>
        {{ form.csrf_token }}
        {{ render_field(form.password) }}
        {{ render_field(form.confirm_password) }}
        {{ form.submit() }}
    </form>
</div>
{% endblock %}

sns_applicatin/flaskr/templates/user.html
{% from "_formhelpers.html" import render_field %}
{% extends "base.html" %}
{% block title %}
ユーザー情報編集画面 - {{ super() }}
{% endblock %}
{% block content %}
<div class="row">
    <div class="col-lg-8 offset-lg-4">
    {% for message in get_flashed_messages() %}
    {{ message }}
    {% endfor %}
    </div>
    <div class="col-lg-2 offset-lg-2">
        {% if current_user.picture_path %}
        <img class="user-image-big" src="{{url_for('static', filename=current_user.picture_path)}}">
        {% endif %}
    </div>
    <div class="col-lg-4 offset-lg-2">
        <form method="POST" enctype="multipart/form-data">
            {{ form.csrf_token }}
            {{ render_field(form.username, value=current_user.username) }}
            {{ render_field(form.email, value=current_user.email) }}
            {{ render_field(form.picture_path) }}
            {{ form.submit() }}
        </form>
        <a href="{{url_for('app.change_password')}}">パスワードを変更する</a>
    </div>
</div>
{% endblock %}

sns_applicatin/flaskr/templates/user_search.html
{% from "_formhelpers.html" import render_field %}
{% extends "base.html" %}
{% block title %}
ユーザー検索 - {{ super() }}
{% endblock %}
{% block content %}
<div class="jumbotoron">
    <p>ユーザー検索画面</p>
</div>
<div class="row">
    <div class="col-lg-12">
        <form method="GET">
            {{ form.csrf_token }}
            {{ render_field(form.username) }}
            {{ form.submit() }}
        </form>
    </div>
    <div class="col-lg-12">
        {% if users %}
        <table class="table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>ユーザー画像</th>
                    <th>ユーザー名</th>
                    <th>申請ボタン</th>
                </tr>
            </thead>
            <tbody>
                {% for user in users %}
                <tr>
                    <th>{{ loop.index }}</th>
                    {% if user.picture_path %}
                    <th>
                        <img class="user-image-small" src="{{ url_for('static', filename=user.picture_path) }}">
                    </th>
                    {% else %}
                    <th></th>
                    {% endif %}
                    <th>{{ user.username }}</th>
                    <th>{% if user.joined_status_from_to == 2 or user.joined_status_to_from == 2 %}
                        友達
                        {% elif user.joined_status_from_to == 1 %}
                        友達申請中
                        {% elif user.joined_status_to_from == 1 %}
                        <form method="POST" action="{{url_for('app.connect_user')}}">
                            {{ connect_form.csrf_token }}
                            {{ connect_form.connect_condition(value='accept') }}
                            {{ connect_form.to_user_id(value=user.id) }}
                            {{ connect_form.submit(class='btn btn-primary', value='友達申請を承認する') }}
                        </form>
                        {% else %}
                        <form method="POST" action="{{ url_for('app.connect_user') }}">
                            {{ connect_form.csrf_token }}
                            {{ connect_form.connect_condition(value='connect') }}
                            {{ connect_form.to_user_id(value=user.id) }}
                            {{ connect_form.submit(class='btn btn-primary', value='友達申請する') }}
                        </form>
                        {% endif %}
                    </th>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% if prev_url %}
            <a href="{{ prev_url }}">前へ</a>
        {% endif %}
        {% if next_url %}
            <a href="{{ next_url }}">次へ</a>
        {% endif %}
        {% endif %}
    </div>
</div>
{% endblock %}